### ISSUE TITLE
Server running twice?

### ISSUE THREAD

**Issue by Integralist** [spurious-io/server#21]
> looks like an error but the service is actually running - it's like it's trying to start it twice

```bash
± spurious-server start
Checking if docker daemon is available...
Starting server...
Started with pid: #32704
/Users/markmcdonnell/.gem/ruby/2.0.0/gems/eventmachine-1.0.6/lib/eventmachine.rb:526:in `start_tcp_server': no acceptor (port is in use or requires root privileges) (RuntimeError)
        from /Users/markmcdonnell/.gem/ruby/2.0.0/gems/eventmachine-1.0.6/lib/eventmachine.rb:526:in `start_server'
        from /Users/markmcdonnell/.gem/ruby/2.0.0/gems/spurious-server-0.6.1/lib/spurious/server.rb:9:in `block in handle'
        from /Users/markmcdonnell/.gem/ruby/2.0.0/gems/em-synchrony-1.0.4/lib/em-synchrony.rb:40:in `call'
        from /Users/markmcdonnell/.gem/ruby/2.0.0/gems/em-synchrony-1.0.4/lib/em-synchrony.rb:40:in `block (2 levels) in synchrony'
```

**Comment by stevenjack** [comment]
This was fixed in https://github.com/spurious-io/server/pull/12, as previously the pid was stored in /tmp and periodically would be flushed out so the server would think that the process wasn't running and would try and start it again on the same port number resulting in the above error.
